
import React, { useState } from 'react';
import { Category, JobEntry, AdSettings, IndianState, Qualification } from '../types';
import { addJob, getJobs, deleteJob, getAdSettings, saveAdSettings } from '../db';
import { searchLatestJobs } from '../geminiService';

interface AdminPanelProps {
  onUpdate: () => void;
}

const AdminPanel: React.FC<AdminPanelProps> = ({ onUpdate }) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'quick_post' | 'ai_auto_sync' | 'list'>('ai_auto_sync');
  const [quickTitle, setQuickTitle] = useState('');

  const [formData, setFormData] = useState<Partial<JobEntry>>({
    title: '',
    department: '',
    category: Category.LATEST_JOB,
    state: 'Others',
    qualification: '12th Pass',
    link: '',
    isUrgent: false
  });

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (password === 'admin123') setIsAuthenticated(true);
  };

  const handleQuickPostAI = async () => {
    if (!quickTitle.trim()) return;
    setLoading(true);
    try {
      const result = await searchLatestJobs(quickTitle);
      addJob({
        title: result.data.postName,
        department: quickTitle,
        category: Category.LATEST_JOB,
        state: 'Others',
        qualification: 'Graduate',
        link: result.data.officialUrl,
        description: result.data.importantDates,
        lastDate: result.data.importantDates,
        totalPosts: result.data.totalPosts,
        eligibility: result.data.eligibility,
        ageLimit: result.data.ageLimit,
        fee: result.data.fee,
        importantDates: result.data.importantDates
      } as any);
      onUpdate();
      alert('Success! Job Generated by Title & Published.');
      setQuickTitle('');
      setActiveTab('list');
    } catch (e) {
      alert('Could not find data for this title. Please use Manual Post.');
    } finally {
      setLoading(false);
    }
  };

  const handleMassAutoSync = async () => {
    setLoading(true);
    try {
      const targetDepts = ['Staff Selection Commission', 'Railway Recruitment Board', 'UP Police Recruitment', 'UPSC Delhi', 'Army Bharti Rally'];
      for (const dept of targetDepts) {
        const result = await searchLatestJobs(dept);
        addJob({
          title: result.data.postName,
          department: dept,
          category: Category.LATEST_JOB,
          state: 'Others',
          qualification: '12th Pass',
          link: result.data.officialUrl,
          description: result.data.importantDates,
          lastDate: result.data.importantDates,
          totalPosts: result.data.totalPosts,
          eligibility: result.data.eligibility,
          ageLimit: result.data.ageLimit,
          fee: result.data.fee,
          importantDates: result.data.importantDates
        } as any);
      }
      onUpdate();
      alert('Mass AI Sync Successful! 5 Latest Notifications Added.');
      setActiveTab('list');
    } catch (e) {
      alert('Mass Sync Error. Check Internet/API.');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmitManual = (e: React.FormEvent) => {
    e.preventDefault();
    addJob(formData as any);
    setFormData({ title: '', department: '', category: Category.LATEST_JOB, state: 'Others', qualification: '12th Pass', link: '', isUrgent: false });
    onUpdate();
    alert('Manual Post Published!');
    setActiveTab('list');
  };

  if (!isAuthenticated) {
    return (
      <div className="flex justify-center py-24">
        <div className="bg-white p-12 rounded-2xl shadow-2xl border-t-[12px] border-[#ff0000] w-full max-w-md text-center">
          <h2 className="text-3xl font-black mb-8 uppercase italic text-[#000080]">ADMIN PORTAL</h2>
          <form onSubmit={handleLogin} className="space-y-6">
            <input type="password" placeholder="ENTER ACCESS KEY" className="w-full p-5 border-2 rounded-xl font-black text-center text-xl tracking-widest focus:border-[#ff0000] outline-none" value={password} onChange={(e) => setPassword(e.target.value)} />
            <button type="submit" className="w-full py-5 bg-[#000080] text-white font-black rounded-xl hover:bg-[#ff0000] transition-all text-lg shadow-xl uppercase">AUTHENTICATE</button>
          </form>
          <p className="text-[11px] mt-8 text-gray-400 font-bold uppercase tracking-[0.3em]">Protected by SARKARI RESULT LIVE</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-3xl shadow-2xl border-4 border-[#000080] overflow-hidden">
      <div className="bg-[#000080] text-white p-6 flex flex-col md:flex-row justify-between items-center gap-4">
         <h2 className="text-2xl font-black uppercase italic tracking-tighter">CENTRAL CONTROL PANEL</h2>
         <div className="flex flex-wrap justify-center gap-2 bg-white/10 p-1.5 rounded-2xl">
            <button onClick={() => setActiveTab('ai_auto_sync')} className={`px-6 py-2.5 rounded-xl text-[10px] font-black uppercase transition-all ${activeTab === 'ai_auto_sync' ? 'bg-[#ff0000] shadow-lg' : 'hover:bg-white/5'}`}>Mass AI Sync</button>
            <button onClick={() => setActiveTab('quick_post')} className={`px-6 py-2.5 rounded-xl text-[10px] font-black uppercase transition-all ${activeTab === 'quick_post' ? 'bg-[#ff0000] shadow-lg' : 'hover:bg-white/5'}`}>Quick Title Post</button>
            <button onClick={() => setActiveTab('list')} className={`px-6 py-2.5 rounded-xl text-[10px] font-black uppercase transition-all ${activeTab === 'list' ? 'bg-[#ff0000] shadow-lg' : 'hover:bg-white/5'}`}>Manage Live</button>
         </div>
      </div>

      <div className="p-10">
        {activeTab === 'ai_auto_sync' && (
          <div className="text-center space-y-8 py-10 max-w-2xl mx-auto">
             <div className="w-28 h-28 bg-[#ff0000] text-white rounded-full flex items-center justify-center mx-auto shadow-2xl animate-pulse text-5xl">
                ⚡
             </div>
             <h3 className="text-3xl font-black text-[#000080] uppercase">1-CLICK AI MASS SYNC</h3>
             <p className="text-sm font-bold text-gray-500 leading-relaxed uppercase">Pressing this button will trigger Gemini AI to scan top government recruitment boards (SSC, Railway, UP Police) and automatically update your portal with the latest 5 notices.</p>
             <button onClick={handleMassAutoSync} disabled={loading} className="w-full py-6 bg-[#ff0000] text-white rounded-2xl font-black uppercase text-xl shadow-2xl hover:scale-[1.02] transition-all disabled:opacity-50 border-b-8 border-red-900">
                {loading ? 'AI IS SCANNING THE WEB...' : 'START AUTO-PILOT SYNC NOW'}
             </button>
          </div>
        )}

        {activeTab === 'quick_post' && (
          <div className="space-y-12 py-10">
             <div className="bg-blue-50 p-10 rounded-[2.5rem] border-2 border-[#000080] text-center">
                <h4 className="text-xl font-black text-[#000080] mb-6 uppercase">AI Quick Post (By Title Only)</h4>
                <div className="flex flex-col md:flex-row gap-3">
                   <input 
                      type="text" 
                      placeholder="e.g. SSC GD 2025 New Update" 
                      className="flex-1 p-5 rounded-2xl border-2 border-gray-200 font-black text-lg focus:border-[#ff0000] outline-none" 
                      value={quickTitle} 
                      onChange={(e) => setQuickTitle(e.target.value)} 
                   />
                   <button onClick={handleQuickPostAI} disabled={loading} className="bg-[#ff0000] text-white px-10 py-5 rounded-2xl font-black uppercase shadow-xl hover:bg-red-700 transition-all disabled:opacity-50">
                      {loading ? 'Extracting...' : 'Generate & Publish'}
                   </button>
                </div>
                <p className="mt-4 text-[11px] font-bold text-blue-400 uppercase italic">*AI will automatically fetch Eligibility, Dates, and Link from the web.</p>
             </div>

             <div className="relative">
                <div className="absolute inset-0 flex items-center"><div className="w-full border-t-2 border-dashed border-gray-200"></div></div>
                <div className="relative flex justify-center text-xs uppercase font-black"><span className="bg-white px-4 text-gray-400 tracking-[0.5em]">OR MANUAL ENTRY</span></div>
             </div>

             <form onSubmit={handleSubmitManual} className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <input type="text" placeholder="Job/Result Title" className="p-4 border-2 rounded-xl font-bold uppercase text-xs" value={formData.title} onChange={(e) => setFormData({...formData, title: e.target.value})} required />
                <input type="text" placeholder="Official URL" className="p-4 border-2 rounded-xl font-bold" value={formData.link} onChange={(e) => setFormData({...formData, link: e.target.value})} required />
                <select className="p-4 border-2 rounded-xl font-black text-xs uppercase" value={formData.category} onChange={(e) => setFormData({...formData, category: e.target.value as Category})}>
                   {Object.values(Category).map(c => <option key={c} value={c}>{c}</option>)}
                </select>
                <select className="p-4 border-2 rounded-xl font-black text-xs uppercase" value={formData.qualification} onChange={(e) => setFormData({...formData, qualification: e.target.value as Qualification})}>
                   {['10th Pass', '12th Pass', 'ITI/Diploma', 'Graduate', 'Post Graduate'].map(q => <option key={q} value={q}>{q}</option>)}
                </select>
                <div className="bg-red-50 p-4 rounded-xl flex items-center gap-4 border-2 border-red-100 md:col-span-2">
                   <input type="checkbox" className="w-8 h-8 rounded-lg" checked={formData.isUrgent} onChange={(e) => setFormData({...formData, isUrgent: e.target.checked})} />
                   <label className="font-black uppercase text-[#ff0000] text-sm tracking-widest">Mark as FLASH/URGENT UPDATE</label>
                </div>
                <button type="submit" className="md:col-span-2 py-6 bg-[#000080] text-white font-black uppercase rounded-2xl shadow-2xl text-xl hover:bg-[#ff0000] transition-all">Publish Manual Post</button>
             </form>
          </div>
        )}

        {activeTab === 'list' && (
          <div className="border-4 border-gray-100 rounded-3xl overflow-hidden shadow-inner max-h-[600px] overflow-y-auto no-scrollbar">
             <table className="w-full text-left border-collapse">
                <thead className="bg-gray-100 text-gray-500 font-black text-[10px] uppercase">
                   <tr>
                      <th className="p-5">Job/Notice Title</th>
                      <th className="p-5">Section</th>
                      <th className="p-5 text-right">Control</th>
                   </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                   {getJobs().map(j => (
                     <tr key={j.id} className="hover:bg-gray-50 transition-colors">
                        <td className="p-5 font-black text-[#000080] uppercase text-xs truncate max-w-[200px]">{j.title}</td>
                        <td className="p-5"><span className="bg-blue-100 text-blue-700 text-[9px] font-black px-3 py-1 rounded-full uppercase">{j.category}</span></td>
                        <td className="p-5 text-right">
                           <button onClick={() => { if(confirm('Permanently delete this post?')) { deleteJob(j.id); onUpdate(); } }} className="text-[#ff0000] font-black text-[10px] border-2 border-[#ff0000] px-4 py-1.5 rounded-lg hover:bg-[#ff0000] hover:text-white transition-all">DELETE</button>
                        </td>
                     </tr>
                   ))}
                </tbody>
             </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminPanel;
